name: 'CI Build'
description: builds the container image.
branding:
  icon: 'layers'
  color: 'gray-dark'

outputs:
  image-tag-commit:
    description: "the image repository path with the the commit id as the tag."
    value: ${{ steps.container-build.outputs.image-tag-commit }}

runs:
  using: 'composite'
  steps:
    - name: container-build
      id: container-build
      shell: bash
      run: |
        echo "====> make build"
        # GIT_SHA for pull request events is the last merge commit of the pull request merge branch.
        # It is not the commit sha we're after. the head commit of the pull request is github.event.pull_request.head.sha
        export GIT_SHORT_COMMIT="$(echo ${{ github.event.pull_request.head.sha }}| cut -c 1-7)"
        make build

        make print-exports FILTER=IMAGE_TAG_COMMIT
        echo "image-tag-commit=$(make print-exports FILTER=IMAGE_TAG_COMMIT)" >> $GITHUB_OUTPUT
