name: build container image

on:
  pull_request:

env:
  REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"

jobs:
  build:
    name: build image
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: make-registry-login
        run: |
          make registry-login

      - name: make-build
        run: |
          make build

      - name: make-push-registry
        run: |
           make push-registry
