name: build container image

on:
  pull_request:

env:
  REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"

jobs:
  build:
    name: build image
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: make-registry-login
        run: |
          make registry-login

      - name: make-build
        run: |
          # GIT_SHA for pull request events is the last merge commit of the pull request merge branch.
          # It is not the commit sha we're after. the head commit of the pull request is github.event.pull_request.head.sha

          export GIT_SHORT_COMMIT="$(echo ${{github.event.pull_request.head.sha }}| cut -c 1-7)"
          make build

      - name: make-push-registry
        run: |
           export GIT_SHORT_COMMIT="$(echo ${{github.event.pull_request.head.sha }}| cut -c 1-7)"
           make push-registry
