# publishes an image where the version is referenced in a file

name: publish container image

on:
  push:
    branches:
      - main

env:
  REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"

jobs:
  release-semver:
    name: release-semver
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: write
      pull-requests: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: action-container-init
        uses: ./actions/container-init

      - name: make-registry-login
        run: |
          make registry-login

      - name: action-container-release
        uses: ./actions/container-release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
