name: publish container image

on:
  push:
    branches:
      - main

env:
  REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
  REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASSWORD }}"

jobs:
  push-image:
    name: resolve image tag
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: make-registry-login
        run: |
          make registry-login

      - name: make-release
        run: |
          make release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
